owner: Representaciones-Marti
repo: status

# User agent personalizado para evitar bloqueos
user-agent: Mozilla/5.0 (compatible; Status/1.0)

sites:
  - name: "Shop"
    url: https://repremarti.es
    maxResponseTime: 30000

  - name: "Cloud"
    url: https://cloud.repremarti.es
    maxResponseTime: 30000

  - name: "Billing"
    url: https://odoo.repremarti.es
    maxResponseTime: 30000

  - name: "Mail"
    url: mail.repremarti.es
    port: 25
    check: "tcp-ping"

  - name: "Webmail"
    url: https://webmail.repremarti.es
    maxResponseTime: 30000


scheduledMaintenances:
  - name: "Backup diario"
    description: "Los servicios pueden estar temporalmente no disponibles debido al backup automático."
    start: "03:00"
    end: "03:40"
    schedule: "0 3 * * *"  # Cambiar "cron" por "schedule"

status-website:
  cname: status.repremarti.es
  name: RepreMarti Status
  logoUrl: https://repremarti.es/img/logo-1727095273.webp
  favicon: https://repremarti.es/img/favicon.ico
  introTitle: "**Estado de los servicios de RepreMarti**"
  introMessage: Monitoreo en tiempo real de nuestros servicios principales.
  theme: light
  
  navbar:
    - title: Status
      href: /
    - title: Sitio Web
      href: https://repremarti.es

# Notificaciones
assignees:
  - JoseManuelPedraja

# Personalización
i18n:
  footer: "© 2025 repremarti.es"
  
commitMessages:
  commitAuthorName: "RepreMarti Status Bot"
  commitAuthorEmail: "josemanuel@pedraja.es"

skipDescriptionIssues: true
skipTopicsIssues: true

